#!/bin/bash
APP_HOME="$HOME/.nf-test"
APP_JAR="nf-test.jar"

if test -f "${APP_HOME}/${APP_JAR}"; then
  FILE_PATH_JAR=${APP_HOME}/${APP_JAR}
else
  FOLDER=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
  FILE_PATH_JAR=${FOLDER}/${APP_JAR}
fi

export JAVA_PROGRAM_ARGS=`echo "$@"`
java -Xmx10G -jar "${FILE_PATH_JAR}" $JAVA_PROGRAM_ARGS
